### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Maiskiy13** [Xenon-Bot/support#1]
I have been using the bot for a long time, it sometimes signed for a maximum of 5 minutes, but today it loads the server for the third hour, I stopped it and loaded it again, but it takes a very long time to load, what's the problem?  Am I the only one having this problem or other users too?

**Comment by merlinfuchs** [comment]
This is not the place for support questions. https://xenon.bot/discord

**Comment by Maiskiy13** [comment]
Interestingly, I was sent from there to you
--
Отправлено из Mail.ru для Android среда, 06 июля 2022г., 19:30 +03:00 от Merlin  ***@***.*** :

**Comment by merlinfuchs** [comment]
You probably misunderstood something then, no problem tho. The issue should be fixed btw

**Comment by Maiskiy13** [comment]
Okay, thanks anyway for your help and for wasting your time with me, sorry
--
Отправлено из Mail.ru для Android среда, 06 июля 2022г., 21:09 +03:00 от Merlin  ***@***.*** :
